server:
  port: 8888


spring:
  redis:
    cache.clusterNodes: 127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003,127.0.0.1:7004,127.0.0.1:7005,127.0.0.1:7006
    cache.commandTimeout: 5000
  main:
    allow-bean-definition-overriding: true
  data:
    elasticsearch:
      # 集群名
      cluster-name: elasticsearch
      # 连接节点,注意在集群中通信都是9300端口，否则会报错无法连接上！
      cluster-nodes: localhost:9300,119.29.38.169:9300
      repositories:
        # 仓库中数据存储
        enabled: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      direct:
        default-requeue-rejected: true
      simple:
        prefetch: 1
        auto-startup: true
    template:
      retry:
        enabled: true
        initial-interval: 2s
  # mail
  mail:
    host: smtp.163.com
    username: ldm112358@163.com
    password: 258692bb
    from: ldm112358@163.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  shardingsphere:
    datasource:
      names: master,slave
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.164.134:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT&useSSL=false
        username: root
        password: root
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.164.134:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT&useSSL=false
        username: root
        password: root
      masterslave:
        load-balance-algorithm-type: round_robin
        name: dataSource
        master-data-source-name: master
        slave-data-source-names: slave
    props:
      sql:
        show: true
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.ldm.entity  # 注意：对应实体类的路径
  configuration:
    map-underscore-to-camel-case: true
netty:
  socket:
    io:
      host: localhost
      port: 9999
