server:
  port: 9888
spring:
  datasource:
    name: mysql_test
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://rm-wz9b75yo746sc35so6o.mysql.rds.aliyuncs.com:3306/app?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT&useSSL=false
      username: mytest
      password: zxc++123
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
  redis:
    cache.clusterNodes: 8.129.63.242:7000,8.129.63.242:7001,8.129.63.242:7002,47.115.53.27:7003,47.115.53.27:7004,47.115.53.27:7005
    cache.commandTimeout: 5000
  main:
    allow-bean-definition-overriding: true
  data:
    elasticsearch:
      cluster-name: my-application
#      # 连接节点,注意在集群中通信都是9300端口，否则会报错无法连接上！
      cluster-nodes: localhost:9300
      repositories:
        # 仓库中数据存储
        enabled: true
  rabbitmq:
    host: 8.129.63.242
    port: 5672
    username: lidongming
    password: lidongming
    virtual-host: /
    publisher-confirms: true
    publisher-returns: true
    listener:
      direct:
        default-requeue-rejected: true
      simple:
        prefetch: 1
        auto-startup: true
    template:
      retry:
        enabled: true
        initial-interval: 2s
      mandatory: true
  # mail
  mail:
    host: smtp.163.com
    username: ldm112358@163.com
    password: 12345678
    from: ldm112358@163.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.ldm.entity  # 注意：对应实体类的路径
  configuration:
    map-underscore-to-camel-case: true
#netty:
#  socket:
#    io:
#      host: 8.129.63.242
#      port: 9999
#  spring.shardingsphere.datasource.names=master,slave
#
#  # 主数据源
#  spring.shardingsphere.datasource.master.type=com.alibaba.druid.pool.DruidDataSource
#  spring.shardingsphere.datasource.master.driver-class-name=com.mysql.cj.jdbc.Driver
#  spring.shardingsphere.datasource.master.url=jdbc:mysql://192.168.164.134:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT&useSSL=false
#  spring.shardingsphere.datasource.master.username=root
#  spring.shardingsphere.datasource.master.password=123456
#
#  # 从数据源
#  spring.shardingsphere.datasource.slave.type=com.alibaba.druid.pool.DruidDataSource
#  spring.shardingsphere.datasource.slave.driver-class-name=com.mysql.cj.jdbc.Driver
#  spring.shardingsphere.datasource.slave.url=jdbc:mysql://192.168.164.129:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT&useSSL=false
#  spring.shardingsphere.datasource.slave.username=root
#  spring.shardingsphere.datasource.slave.password=123456
#
#  # 读写分离配置
#  spring.shardingsphere.masterslave.load-balance-algorithm-type=round_robin
#  spring.shardingsphere.masterslave.name=dataSource
#  spring.shardingsphere.masterslave.master-data-source-name=master
#  spring.shardingsphere.masterslave.slave-data-source-names=slave
#
#  # 显示SQL
#  spring.shardingsphere.props.sql.show=true
#  spring.main.allow-bean-definition-overriding=true